CREDITCARD = "creditcard"
DEBITCARD = "debitcard"
CTYPES = [CREDITCARD, DEBITCARD]

DEBIT = "debit"
CREDIT = "credit"
PAID_BY_YOU = "paid_by_you"
UNPAID_EXPENSE = "unpaid_expense"
SETTLED_BY_PARTY = "settled_by_party"
SETTLED_BY_YOU = "settled_by_you"
SPLIT = "split"

TTYPES = [DEBIT, CREDIT, PAID_BY_YOU, UNPAID_EXPENSE, SETTLED_BY_PARTY, SETTLED_BY_YOU, SPLIT]
CREDIT_TRANSACTIONS = [CREDIT, SETTLED_BY_PARTY]
