default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: my-postgres-container
  username: myapp_user           # Replace with your PostgreSQL username
  password: myapp_password       # Replace with your PostgreSQL password

development:
  <<: *default
  database: audit  # Replace with your production database name
  host: localhost  # Use the container name defined in docker-compose.yml
  port: 5432                  # PostgreSQL container's default port
  username: sathwik       # Replace with your PostgreSQL username
  password: sath139   # Replace with your development database name

test:
  <<: *default
  database: audit_test         # Replace with your test database name

production:
  <<: *default
  database: audit  # Replace with your production database name
  host: my-postgres-container  # Use the container name defined in docker-compose.yml
  port: 5432                  # PostgreSQL container's default port
  username: sathwik       # Replace with your PostgreSQL username
  password: sath139    # Replace with your PostgreSQL password

# RDS
# development:
#   adapter: postgresql
#   encoding: utf8
#   database: audit_dev
#   pool: 5
#   username: sathwik
#   password: sath1399
#   host: rds-database.cul8kbporqwf.ap-south-1.rds.amazonaws.com
#   port: 5432 # Default PostgreSQL port

# production:
#   adapter: postgresql
#   encoding: utf8
#   database: audit
#   pool: 5
#   username: sathwik
#   password: sath1399
#   host: rds-database.cul8kbporqwf.ap-south-1.rds.amazonaws.com
#   port: 5432 # Default PostgreSQL port
