default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: my-postgres-container
  username: myapp_user           # Replace with your PostgreSQL username
  password: myapp_password       # Replace with your PostgreSQL password

development:
  <<: *default
  database: audit  # Replace with your production database name
  host: localhost  # Use the container name defined in docker-compose.yml
  port: 5432                  # PostgreSQL container's default port
  username: sathwik       # Replace with your PostgreSQL username
  password: sath139   # Replace with your development database name

test:
  <<: *default
  database: audit_test         # Replace with your test database name

production:
  <<: *default
  database: audit  # Replace with your production database name
  host: my-postgres-container  # Use the container name defined in docker-compose.yml
  port: 5432                  # PostgreSQL container's default port
  username: sathwik       # Replace with your PostgreSQL username
  password: sath139    # Replace with your PostgreSQL password
