version: '3'
services:
  rails:
    image: sathwik139/audit:rails-v3
    command: >
      /bin/sh -c "rails db:drop && rails db:create && rails db:migrate && puma -C config/puma.rb"
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
      HOST_IP: localhost
    depends_on:
      - redis
    ports:
      - "3001:3001"
  sidekiq:
    image: sathwik139/audit:rails-v3
    command: bundle exec sidekiq -c 2 -q low
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
      HOST_IP: localhost
    depends_on:
      - redis
  redis:
    image: redis:latest
  react:
    image: sathwik139/audit:react-v2
    environment:
      VITE_HOST: localhost
      VITE_PORT: 5173
    ports:
      - "5173:5173"
