version: '3'
services:
  rails:
    image: audit-rails:v1.1
    command: >
      /bin/sh -c "rails db:create && rails db:migrate && puma -C config/puma.rb"
    environment:
      RAILS_ENV: production
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
      REDIS_URL: redis://redis:6379/1
      HOST_IP: localhost
      GMAIL_EMAIL: 'audit.app.mail@gmail.com'
      GMAIL_PASSWORD: 'zuka ydyi punm bzyb'
    depends_on:
      - redis
    ports:
      - "3001:3001"
  sidekiq:
    image: audit-rails:v1.1
    command: bundle exec sidekiq -c 2 -q low
    environment:
      RAILS_ENV: production
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
      REDIS_URL: redis://redis:6379/1
      HOST_IP: localhost
      GMAIL_EMAIL: 'audit.app.mail@gmail.com'
      GMAIL_PASSWORD: 'zuka ydyi punm bzyb'
    depends_on:
      - redis
  redis:
    image: redis:latest
  react:
    image: audit-react:v6
    environment:
      VITE_HOST: localhost
      VITE_PORT: 4173
    ports:
      - "4173:4173"
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: audit
      POSTGRES_USER: sathwik
      POSTGRES_PASSWORD: sath139