version: '3'
services:
  rails:
    image: sathwik139/audit:rails-v5
    command: >
      /bin/sh -c "rails db:drop && rails db:create && rails db:migrate && puma -C config/puma.rb"
    environment:
      RAILS_ENV: production
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
      REDIS_URL: redis://redis:6379/1
      HOST_IP: localhost
      GMAIL_EMAIL: 'audit.app.mail@gmail.com'
      GMAIL_PASSWORD: 'zuka ydyi punm bzyb'
    depends_on:
      - redis
    ports:
      - "3001:3001"
  sidekiq:
    image: sathwik139/audit:rails-v5
    command: bundle exec sidekiq -c 2 -q low
    environment:
      RAILS_ENV: production
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
      REDIS_URL: redis://redis:6379/1
      HOST_IP: localhost
      GMAIL_EMAIL: 'audit.app.mail@gmail.com'
      GMAIL_PASSWORD: 'zuka ydyi punm bzyb'
    depends_on:
      - redis
  redis:
    image: redis:latest
  react:
    image: sathwik139/audit:react-v4
    environment:
      VITE_HOST: localhost
      VITE_PORT: 5173
    ports:
      - "5173:5173"
